docs: added documentation for AKS configuration and deployment
Multiwoven/docs pull request #50
Opened 2024-05-07 15:02 UTC by AngeloB-AIS

#### PR Type:
- [x] New documentation
- [ ] Documentation Update
- [ ] Fix/Error Correction
- [ ] Typographical Error
- [ ] Other (Specify)

#### Detailed Description:
docs: added documentation for AKS configuration and deployment 

#### Checklist:
- [x] I have reviewed the contribution guidelines.
- [x] My documentation is in the correct directory/folder.
- [x] My changes do not duplicate existing documentation.
- [x] I have used spell check and my document is grammatically correct.
- [ ] If relevant, I have updated or added to the FAQs or Glossary sections.

2024-05-07 15:27 UTC, subintp commented on guides/setup/aks.mdx
> +    * Please refer to the **Helm Charts** section of our guide to proceed with your installation of Multiwoven!
hyperlink helm chart link

2024-05-07 15:27 UTC, subintp requested changes

2024-05-07 15:27 UTC, subintp commented on guides/setup/aks.mdx
> +    * Navigate to your Azure subscription and select a Resource Group or, if necessary, start by creating a new Resource Group.
Add screenshots for every steps

2024-05-09 21:20 UTC, AngeloB-AIS commented on guides/setup/aks.mdx
> +    * Navigate to your Azure subscription and select a Resource Group or, if necessary, start by creating a new Resource Group.
@subintp done

2024-05-09 21:21 UTC, AngeloB-AIS commented on guides/setup/aks.mdx
> +    * Please refer to the **Helm Charts** section of our guide to proceed with your installation of Multiwoven!
@subintp done

2024-05-09 21:24 UTC, AngeloB-AIS commented
@subintp , I didn't realize the structure of main had changed so dramatically since I created this PR. I'm going to cancel this PR, create a new branch off of main and add my stuff there. I've saved the contents of the file, I just need to move it.

2024-05-09 21:34 UTC, closed without merging