docs: added documentation for s3 source connector
Multiwoven/docs pull request #64
Opened 2024-06-12 18:48 UTC by pabss-ai2

2024-06-20 13:25 UTC, subintp requested changes

2024-07-09 10:12 UTC, karthik-sivadas commented on guides/data-integration/sources/amazon_s3.mdx
> +This page describes how to add AWS S3 as a source to Census.
Please correct our application name 😅

2024-07-09 10:15 UTC, karthik-sivadas approved these changes
LGTM. Have added a small nitpick

2024-08-13 11:35 UTC, afthabvp approved these changes

2024-08-13 11:35 UTC, merged